app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/config', function () {
    $exitCode = Artisan::call('scaffold:config');
});
Route::get('/configp', function () {
    $exitCode = Artisan::call('scaffold:config',['-p'=>'test']);
});
Route::get('/project', function () {
    $exitCode = Artisan::call('scaffold:project');
});
Route::get('/route', function () {
    $exitCode = Artisan::call('scaffold:route');
});
*/
Route::group([
    'prefix' => 'product',
    'as' => 'product.',
    'namespace' => 'Product',

], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'ProductController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'ProductController@create']);
    Route::post('save',        ['as' => 'save',   'uses' => 'ProductController@save']);

    Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'ProductController@edit']);
    Route::any('update/{id}',  ['as' => 'update', 'uses' => 'ProductController@update']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'ProductController@delete']);

    include 'Routes/Product/ProductFile.php';
});


        Route::group([
            'prefix' => 'role',
            'as' => 'role.',
            'namespace' => 'Role',

        ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'RoleController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'RoleController@create']);
            Route::post('save',        ['as' => 'save',   'uses' => 'RoleController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'RoleController@edit']);
            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'RoleController@update']);

            Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'RoleController@delete']);

        });


        Route::group([
            'prefix' => 'user',
            'as' => 'user.',
            'namespace' => 'User',

        ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'UserController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'UserController@create']);
            Route::post('save',        ['as' => 'save',   'uses' => 'UserController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'UserController@edit']);
            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'UserController@update']);

            Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'UserController@delete']);

        });

include 'extraAdmin_routes.php';

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/User/UserController.php
<?php
namespace App\Http\Controllers\Admin\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Admin\User\User;
use Illuminate\Http\Request;

class UserController extends Controller {

    public function index()
    {
        $user = User::orderBy('id', 'desc')->paginate(10);

        return view('admin.user.user.index', [
            'user' => $user
        ]);
    }


    public function create()
    {
        return view('admin.user.user.create');
    }


    public function save(Request $request)
    {
        $user = new User($request->all());

        $user->save();

        return redirect()->route('user.index');
    }


    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.user.user.edit', [
            'user' => $user
        ]);
    }


    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->update($request->all());

        return redirect()->route('user.index');
    }


    public function delete($id)
    {
        $user = User::where('id', '=', $id);
        $user->delete();

        return redirect()->back();
    }

}

app/Http/Controllers/User/UserController.php
<?php
namespace App\Http\Controllers\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\User\User;
use Illuminate\Http\Request;

class UserController extends Controller {

    public function index()
    {
        $user = User::orderBy('id', 'desc')->paginate(10);

        return view('user.user.index', [
            'user' => $user
        ]);
    }


    public function create()
    {
        return view('user.user.create');
    }


    public function save(Request $request)
    {
        $user = new User($request->all());

        $user->save();

        return redirect()->route('user.index');
    }


    public function edit($id)
    {
        $user = User::find($id);

        return view('user.user.edit', [
            'user' => $user
        ]);
    }


    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->update($request->all());

        return redirect()->route('user.index');
    }


    public function delete($id)
    {
        $user = User::where('id', '=', $id);
        $user->delete();

        return redirect()->back();
    }

}

resources/views/user/user/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> User / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('user.save') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('user.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>

            </form>

        </div>
    </div>
@endsection

resources/views/user/user/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> User / Edit #{{ $user->id }}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('user.update', $user->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('user.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/user/user/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> User
            <a class="btn btn-success pull-right" href="{{ route('user.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($user->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($user as $item)
                            <tr>
                                <td>{{ $item->id }}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-warning" href="{{ route('user.edit', $item->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('user.delete', $item->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $user->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection