app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/config', function () {
    $exitCode = Artisan::call('scaffold:config');
});
Route::get('/configp', function () {
    $exitCode = Artisan::call('scaffold:config',['-p'=>'test']);
});
Route::get('/project', function () {
    $exitCode = Artisan::call('scaffold:project');
});
Route::get('/route', function () {
    $exitCode = Artisan::call('scaffold:route');
});
*/
Route::group([
    'prefix' => 'product',
    'as' => 'product.',
    'namespace' => 'Product',

], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'ProductController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'ProductController@create']);
    Route::post('save',        ['as' => 'save',   'uses' => 'ProductController@save']);

    Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'ProductController@edit']);
    Route::any('update/{id}',  ['as' => 'update', 'uses' => 'ProductController@update']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'ProductController@delete']);

    include 'Routes/Product/ProductFile.php';
});


        Route::group([
            'prefix' => 'role',
            'as' => 'role.',
            'namespace' => 'Role',

        ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'RoleController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'RoleController@create']);
            Route::post('save',        ['as' => 'save',   'uses' => 'RoleController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'RoleController@edit']);
            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'RoleController@update']);

            Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'RoleController@delete']);

        });


        Route::group([
            'prefix' => 'user',
            'as' => 'user.',
            'namespace' => 'User',

        ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'UserController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'UserController@create']);
            Route::post('save',        ['as' => 'save',   'uses' => 'UserController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'UserController@edit']);
            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'UserController@update']);

            Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'UserController@delete']);

        });

include 'extraAdmin_routes.php';

app/Http/Controllers/Admin/Role/RoleController.php
<?php
namespace App\Http\Controllers\Admin\Role;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Admin\Role\Role;
use Illuminate\Http\Request;

class RoleController extends Controller {

    public function index()
    {
        $role = Role::orderBy('id', 'desc')->paginate(10);

        return view('admin.role.role.index', [
            'role' => $role
        ]);
    }


    public function create()
    {
        return view('admin.role.role.create');
    }


    public function save(Request $request)
    {
        $role = new Role($request->all());

        $role->save();

        return redirect()->route('role.index');
    }


    public function edit($id)
    {
        $role = Role::find($id);

        return view('admin.role.role.edit', [
            'role' => $role
        ]);
    }


    public function update(Request $request, $id)
    {
        $role = Role::find($id);

        $role->update($request->all());

        return redirect()->route('role.index');
    }


    public function delete($id)
    {
        $role = Role::where('id', '=', $id);
        $role->delete();

        return redirect()->back();
    }

}

app/Http/Controllers/Role/RoleController.php
<?php
namespace App\Http\Controllers\Role;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Role\Role;
use Illuminate\Http\Request;

class RoleController extends Controller {

    public function index()
    {
        $role = Role::orderBy('id', 'desc')->paginate(10);

        return view('role.role.index', [
            'role' => $role
        ]);
    }


    public function create()
    {
        return view('role.role.create');
    }


    public function save(Request $request)
    {
        $role = new Role($request->all());

        $role->save();

        return redirect()->route('role.index');
    }


    public function edit($id)
    {
        $role = Role::find($id);

        return view('role.role.edit', [
            'role' => $role
        ]);
    }


    public function update(Request $request, $id)
    {
        $role = Role::find($id);

        $role->update($request->all());

        return redirect()->route('role.index');
    }


    public function delete($id)
    {
        $role = Role::where('id', '=', $id);
        $role->delete();

        return redirect()->back();
    }

}

resources/views/role/role/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Role / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('role.save') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('role.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>

            </form>

        </div>
    </div>
@endsection

resources/views/role/role/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Role / Edit #{{ $role->id }}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('role.update', $role->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('role.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/role/role/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Role
            <a class="btn btn-success pull-right" href="{{ route('role.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($role->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($role as $item)
                            <tr>
                                <td>{{ $item->id }}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-warning" href="{{ route('role.edit', $item->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('role.delete', $item->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $role->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection